### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nikivazou** [nikivazou/personal#1]
- [ ] thesis  

- [ ] go to payroll
- [ ] schedule gyn exam
- [ ] prepare Friday talk
- [ ] paper review
- [ ] math reviews review
- [ ] read elimination paper, Sec 5
